### ISSUE TITLE
Pre-processing?

### ISSUE THREAD

**Issue by iandkelly** [jpvantassel/hvsrpy#19]
Hi Joseph,

Thanks for putting together this amazing package!

I'm doing some initial exploration with a raw data set collected from East Antarctica and encountered some 'interesting' spectra:
![hvsrpy_Casey_station70_006_HVSR1](https://user-images.githubusercontent.com/77166513/204689944-95b928b7-69d0-4fe9-b26f-76564e15ed58.png)
Being a relative beginner with HVSR processing, I wanted to ask what your recommended data pre-processing steps are before HVSR analysis in _hvsrpy_, beyond the implemented time-domain filtering and spectral smoothing? I understand instrumental response correction may not be necessary if responses across components are similar, but can, e.g., detrending, static shift corrections be implemented in _hvsrpy_? What are the typical steps you take? I'd be grateful for any advice you could give!

Cheers,

Ian

**Comment by jpvantassel** [comment]
Hi @iandkelly,

Glad to hear you are finding _hvsrpy_ useful in your work. Regarding pre-processing, as you noted, band-pass filtering is provided but optional with the default (and my preference) being not to band-pass filter the time series. In addition, detrending of the time series is performed automatically with _hvsrpy_ to avoid artifacts in the frequency spectra. Yes, you are correct, instrument response correction is unnecessary if the three components have similar responses. Other than the aforementioned I am not aware of any other pre-processing techniques for HVSR; if there is something you are looking for specifically I can considering adding it in an upcoming release.

Additionally, it may be of interest to you to see [(Vantassel et al., 2021)](https://doi.org/10.1061/9780784483428.005) that contains a brief discussion of the processing parameters that most-significantly control the HVSR calculation (e.g., window length, smoothing coefficient, and method for combining the horizontal spectra) with some examples.

All the best,
Joe
