### ISSUE TITLE
hvsrpy Community Survey

### ISSUE THREAD

**Issue by jpvantassel** [jpvantassel/hvsrpy#20]
Dear _hvsrpy_ Community,
It is hard to believe but _hvsrpy_ (Vantassel, 2020) has just turned three. Over that time _hvsrpy_ has seen widespread use in the fields of seismology, geophysics, and engineering and a rapidly growing userbase (over 30k downloads & over 45 stars on GitHub). As such, I have decided to undertake the first major overhaul of the _hvsrpy_ codebase to add new features and streamline its API. Throughout this process I am looking for feedback (via this survey https://forms.gle/36aWUKrgGwiYddnSA) to understand how the community currently processes HVSR data and what new features the community would like to see in the future. Your responses are greatly appreciated. Keep an eye out for the release of _hvsrpy_ v2.0.0 later this year.

**Comment by alangi** [comment]
I've filled out the form, but have thought of a feature that may be useful to have pre-built. Some sort of frequency spectrum check to look for specific peaks related to persistant noise from industrial processes and other anthropogenic sources.

**Comment by jpvantassel** [comment]
Dear @alangi,
Thank you for completing the survey; I really appreciate your feedback. A way to identify anthropogenic sources is a great idea. Would implementing a checking process, like how the SESAME clarity criteria is currently implementing be useful to you? For example, you have peak you think may be anthropogenic, you could then isolate that peak and _hvsrpy_ would check if that peak is likely anthropogenic. What are your thoughts on this?

**Comment by alangi** [comment]
Hi @jpvantassel,
I think that there could be a combined approach to anthropogenic noise. There could be an automated check using one of the methods mentioned on page 45 of the SESAME report. The peaks of the noise will likely occur at the same frequency for all three components. This would be a fairly straight forward automated check I'd expect.

Another approach mentioned is if a peak is identified as likely to be anthropogenic then reprocessing with different smoothing factors (also p45) caused it to get narrower and greater in amplitude. This could be applied manually or automatically after identification by the first approach mentioned above.

I think that this would be very valuable.

**Comment by jpvantassel** [comment]
Hi @alangi,
Thank you for this input, I will take a look at getting this introduced into the upcoming release of _hvsrpy_.
All the best,
Joe

**Comment by jpvantassel** [comment]
The community survey has closed thank you to everyone who participated!
