### ISSUE TITLE
Output final results

### ISSUE THREAD

**Issue by mcardenass** [jpvantassel/hvsrpy#26]
In the previous version it was possible to save the final results by
hv. to_file (file_name_out, distribution_f0, distribution_mc, data_format= "hvsrpy").
Is there a way to do the same in this new version?
Thank you

**Comment by jpvantassel** [comment]
@mcardenass,

Yes, this is now supported through the `hvsrpy.object_io` module. An example of how to use the two key functions `hvsrpy.object_io.write_hvsr_object_to_file` and `hvsrpy.object_io.read_hvsr_object_from_file` are provided [here](https://github.com/jpvantassel/hvsrpy/blob/main/examples/example_hvsr_io.ipynb). The change was necessary to support writing and reading text-based summaries of all HVSR objects in one unified interface.

All the best,
Joe

**Comment by mcardenass** [comment]
Joe, thanks for the information. One more request, how extracts the statistical information to a txt file, especially the peak of the average curve and the amplitude. Thanks in advance.
Martin

**Comment by jpvantassel** [comment]
Hi @mcardenass,

This is not currently in the output file, although it probably should be. The solution for now is to access the statistics from the methods of the associated HVSR object. For example: `mean_fn_amplitude`, `mean_fn_frequency`, `std_fn_frequency`, `std_fn_amplitude`, and `mean_curve_peak`. If you have the output files already you can use `hvsrpy.object_io.read_hvsr_object_from_file` to read them back into an object then call the method, without having to reprocess your data.

All the best,
Joe

**Comment by mcardenass** [comment]
Thanks Joe!!

hvsr_from_disk = hvsrpy.object_io.read_hvsr_object_from_file(f"{fname_prefix}.csv")
(fre,amp)=hvsr_from_disk.mean_curve_peak()

Martín

**Comment by jpvantassel** [comment]
That's it!
