### ISSUE TITLE
proble to read SAF in version 2.0

### ISSUE THREAD

**Issue by Adre17** [jpvantassel/hvsrpy#33]
Hi, my name is umberto
i try to read saf file from example_mhvsr_traditional_sesame.ipynb example , 
i copy the example in python script, correct install all package and run the script.

buti get : 
ValueError: Must provide 3 peer files (one per trace) as list or tuple, not <class 'str'>

i use version 2.0.0 of hvrspy 

attachment saf file,

where is my fault? 

[test_001.zip](https://github.com/user-attachments/files/18041332/test_001.zip)

Best regards

**Comment by rkamai** [comment]
I have the exact same problem

**Comment by rkamai** [comment]
Hello, me again.
I have simply multiplied all my data by 10E8 to obtain integers, and it's working.. 
Since we're dealing with a ratio, I'm assuming it shouldn't affect the results I'm after.

**Comment by jpvantassel** [comment]
Hi @rkamai and @Adre17,
From @rkamai last comment, I think this may be the same issue as: https://github.com/jpvantassel/hvsrpy/issues/28#issuecomment-2267662694
Can you try using that solution and see if it fixes it?

**Comment by Adre17** [comment]
Hi for me the problem is the same issue as: https://github.com/jpvantassel/hvsrpy/issues/28#issuecomment-2267662694
with change of line 29 i can read SAF file, Thanks.

Do you plan to debug with an upcoming release?

**Comment by rkamai** [comment]
Hi @jpvantassel , the fix is working. Able to read the saf files now. Thank you!

**Comment by jpvantassel** [comment]
Great, I am going to close the issue. This fix will be included in the next release of _hvsrpy_. This should be in the next few months.
